import type { GuideContent } from "../../types/guideContent";

export const residencePermitContent: Record<"en" | "tr" | "ar" | "ru", GuideContent> = {
  "en": {
    "badgeLabel": "Residence permit guide",
    "heroTitle": "Residence permit (İkamet)",
    "heroDescription": "This guide walks you through applying for your residence permit as an international student in Türkiye, from your first online application to picking up your card.",
    "calloutNote": "The residence permit process is run nationally by Türkiye's Directorate of Migration Management, not by individual universities, so requirements can change and vary slightly by province. Always confirm current steps, documents, and fees with Kocaeli University's International Office and the official e-ikamet system before your appointment.",
    "sections": [
      {
        "id": "overview",
        "title": "Overview",
        "paragraphs": [
          "Every international student staying in Türkiye longer than their entry visa or visa-free period allows must obtain a student residence permit (öğrenci ikamet izni). Turkey does not issue a long-term student visa on its own — you enter on a short-term entry visa or visa-free stamp, then apply for your residence permit after arrival.",
          "The application itself is submitted online through the government's e-ikamet system, and at most universities the International Office collects your physical documents and forwards them to the local Provincial Directorate of Migration Management on your behalf, rather than you dealing with the migration office directly."
        ]
      },
      {
        "id": "documents",
        "title": "Required documents",
        "paragraphs": [
          "While exact requirements can vary slightly by province, you should generally prepare:"
        ],
        "list": {
          "type": "ul",
          "items": [
            "Your passport (original and a photocopy of the identity and visa pages)",
            "The signed residence permit application form generated by e-ikamet",
            "A current student certificate from your department",
            "Valid health insurance that meets the Migration Directorate's minimum coverage requirements",
            "Biometric photos",
            "Proof of address (a dormitory letter, notarized rental agreement, or utility bill depending on where you live)",
            "Receipt confirming payment of the residence permit card fee"
          ]
        }
      },
      {
        "id": "steps",
        "title": "Application steps",
        "list": {
          "type": "ol",
          "items": [
            "Create your application online at e-ikamet.goc.gov.tr, selecting \"first application\" for a student permit.",
            "Print and sign the application form generated at the end.",
            "Gather all required documents listed above.",
            "Submit your documents to Kocaeli University's International Office within the deadline they specify (many universities require this within 15–30 days of creating your online application).",
            "Pay the residence permit card fee and keep your receipt.",
            "Wait for your appointment — many universities batch-submit student files to the migration office rather than sending you individually.",
            "Track your application status on the e-ikamet website.",
            "Once approved, your physical card is mailed to your registered address."
          ]
        }
      },
      {
        "id": "fees",
        "title": "Fees",
        "paragraphs": [
          "Students get meaningfully better fee treatment than most other residence permit categories: the residence permit tax (harç) that applies to short-term and other permit types is generally waived for student permits, meaning students typically only pay the fixed annual document/card fee (belge bedeli) set by the Ministry of Finance.",
          "This card fee changes every year, so don't budget based on a number from an old blog post or a previous student's experience. Check the current amount directly on e-ikamet.gov.tr or with the International Office before you pay."
        ]
      },
      {
        "id": "timeline",
        "title": "Timeline",
        "list": {
          "type": "ul",
          "items": [
            "You must start your application before your current visa or visa-free stay period expires — don't wait until the last week.",
            "Most universities set their own internal deadline (commonly 15–30 days after your online application) for submitting physical documents to the International Office.",
            "Processing time after submission varies by province and can range from a few weeks to a couple of months.",
            "If you're renewing an existing permit rather than applying for the first time, start at least 60 days before your current card expires."
          ]
        }
      },
      {
        "id": "mistakes",
        "title": "Common mistakes",
        "list": {
          "type": "ul",
          "items": [
            "Waiting too long after arrival to start the online application.",
            "Submitting documents to the International Office after their internal deadline, even if your visa hasn't expired yet.",
            "Health insurance that doesn't meet the minimum coverage the Migration Directorate requires.",
            "Not updating the Migration Office after a change of address, passport, or department.",
            "Assuming last year's fee amount is still correct."
          ]
        }
      },
      {
        "id": "tips",
        "title": "Helpful tips",
        "list": {
          "type": "ul",
          "items": [
            "Start your e-ikamet application as early as your university allows — don't wait for a reminder.",
            "Keep digital and physical copies of every document and receipt you submit.",
            "Ask your International Office directly which address-proof document applies to your specific housing situation (dorm vs. private rental).",
            "Save the Migration Management helpline (157) in your phone — it's the official channel for questions about your specific application."
          ]
        }
      },
      {
        "id": "faq",
        "title": "FAQ",
        "faq": [
          {
            "question": "Do I need a separate student visa before arriving?",
            "answer": "No — you enter on a standard entry visa or visa-free stay, then apply for your residence permit after you arrive."
          },
          {
            "question": "Can I leave Türkiye while my application is being processed?",
            "answer": "This depends on your specific situation and current regulations — confirm with the International Office or the Migration Management helpline before booking travel."
          },
          {
            "question": "What happens if I graduate before my permit expires?",
            "answer": "According to guidance some universities have received from the Migration Office, if your card's expiry date is after your graduation date, you may generally stay until the card itself expires — but confirm your specific case with your International Office."
          }
        ]
      }
    ],
    "sourceNoteText": "This guide summarizes the general national process and is not official legal advice. For your specific case, always check",
    "sourceLinks": [
      {
        "label": "e-ikamet.goc.gov.tr",
        "href": "https://e-ikamet.goc.gov.tr"
      }
    ]
  },
  "tr": {
    "badgeLabel": "İkamet izni rehberi",
    "heroTitle": "İkamet izni",
    "heroDescription": "Bu rehber, Türkiye'deki uluslararası bir öğrenci olarak ikamet izni başvurunuzda ilk online başvurudan kartınızı almaya kadar size yol gösterir.",
    "calloutNote": "İkamet izni süreci üniversiteler tarafından değil, Türkiye Göç İdaresi Genel Müdürlüğü tarafından ulusal düzeyde yürütülür, bu yüzden gereksinimler değişebilir ve ile göre farklılık gösterebilir. Randevunuzdan önce güncel adımları, belgeleri ve ücretleri her zaman Kocaeli Üniversitesi Uluslararası Ofisi ve resmi e-ikamet sistemiyle teyit edin.",
    "sections": [
      {
        "id": "overview",
        "title": "Genel Bakış",
        "paragraphs": [
          "Türkiye'de giriş vizesinin veya vizesiz kalma süresinin izin verdiğinden daha uzun süre kalan her uluslararası öğrenci, öğrenci ikamet izni almalıdır. Türkiye tek başına uzun süreli bir öğrenci vizesi vermez — kısa süreli bir giriş vizesi veya vizesiz damga ile girersiniz, ardından geldikten sonra ikamet izni başvurusu yaparsınız.",
          "Başvurunun kendisi devletin e-ikamet sistemi üzerinden online olarak yapılır ve çoğu üniversitede Uluslararası Ofis, sizin göç idaresiyle doğrudan uğraşmanız yerine fiziksel belgelerinizi toplayıp yerel İl Göç İdaresi Müdürlüğü'ne sizin adınıza iletir."
        ]
      },
      {
        "id": "documents",
        "title": "Gerekli Belgeler",
        "paragraphs": [
          "Tam gereksinimler ile göre biraz farklılık gösterebilse de, genellikle şunları hazırlamalısınız:"
        ],
        "list": {
          "type": "ul",
          "items": [
            "Pasaportunuz (kimlik ve vize sayfalarının aslı ve bir fotokopisi)",
            "e-ikamet tarafından oluşturulan imzalı ikamet izni başvuru formu",
            "Bölümünüzden güncel öğrenci belgesi",
            "Göç İdaresi'nin minimum kapsam gereksinimlerini karşılayan geçerli sağlık sigortası",
            "Biyometrik fotoğraflar",
            "Adres belgesi (nerede yaşadığınıza bağlı olarak bir yurt belgesi, noter onaylı kira sözleşmesi veya fatura)",
            "İkamet izni kart ücretinin ödendiğini gösteren makbuz"
          ]
        }
      },
      {
        "id": "steps",
        "title": "Başvuru Adımları",
        "list": {
          "type": "ol",
          "items": [
            "e-ikamet.goc.gov.tr adresinden online başvurunuzu oluşturun, öğrenci izni için \"ilk başvuru\"yu seçin.",
            "Sonunda oluşturulan başvuru formunu yazdırın ve imzalayın.",
            "Yukarıda listelenen tüm gerekli belgeleri toplayın.",
            "Belgelerinizi Kocaeli Üniversitesi Uluslararası Ofisi'nin belirttiği son tarihe kadar teslim edin (birçok üniversite bunu online başvurunuzu oluşturduktan sonra 15-30 gün içinde ister).",
            "İkamet izni kart ücretini ödeyin ve makbuzunuzu saklayın.",
            "Randevunuzu bekleyin — birçok üniversite öğrenci dosyalarını tek tek değil, toplu olarak göç idaresine iletir.",
            "Başvuru durumunuzu e-ikamet web sitesinden takip edin.",
            "Onaylandıktan sonra fiziksel kartınız kayıtlı adresinize postalanır."
          ]
        }
      },
      {
        "id": "fees",
        "title": "Ücretler",
        "paragraphs": [
          "Öğrenciler diğer ikamet izni kategorilerine göre önemli ölçüde daha iyi ücret muamelesi görür: kısa süreli ve diğer izin türlerine uygulanan ikamet izni harcı genellikle öğrenci izinleri için muaf tutulur, yani öğrenciler genellikle yalnızca Maliye Bakanlığı tarafından belirlenen sabit yıllık belge/kart bedelini öder.",
          "Bu kart ücreti her yıl değişir, bu yüzden eski bir blog yazısındaki veya önceki bir öğrencinin deneyimindeki bir rakama göre bütçe yapmayın. Ödeme yapmadan önce güncel tutarı doğrudan e-ikamet.gov.tr üzerinden veya Uluslararası Ofis'ten kontrol edin."
        ]
      },
      {
        "id": "timeline",
        "title": "Zaman Çizelgesi",
        "list": {
          "type": "ul",
          "items": [
            "Mevcut vizeniz veya vizesiz kalma süreniz dolmadan önce başvurunuza başlamalısınız — son haftaya kadar beklemeyin.",
            "Çoğu üniversite, fiziksel belgeleri Uluslararası Ofis'e teslim etmek için kendi iç son tarihini belirler (genellikle online başvurunuzdan sonra 15-30 gün).",
            "Başvuru sonrası işlem süresi ile göre değişir ve birkaç haftadan birkaç aya kadar sürebilir.",
            "İlk kez başvurmak yerine mevcut bir izni yeniliyorsanız, mevcut kartınızın süresi dolmadan en az 60 gün önce başlayın."
          ]
        }
      },
      {
        "id": "mistakes",
        "title": "Yaygın Hatalar",
        "list": {
          "type": "ul",
          "items": [
            "Geldikten sonra online başvuruya başlamak için çok uzun beklemek.",
            "Vizeniz henüz dolmamış olsa bile, belgeleri Uluslararası Ofis'in iç son tarihinden sonra teslim etmek.",
            "Göç İdaresi'nin gerektirdiği minimum kapsamı karşılamayan sağlık sigortası.",
            "Adres, pasaport veya bölüm değişikliğinden sonra Göç İdaresi'ni bilgilendirmemek.",
            "Geçen yılın ücret tutarının hala doğru olduğunu varsaymak."
          ]
        }
      },
      {
        "id": "tips",
        "title": "Faydalı İpuçları",
        "list": {
          "type": "ul",
          "items": [
            "e-ikamet başvurunuza üniversitenizin izin verdiği en erken zamanda başlayın — bir hatırlatma beklemeyin.",
            "Teslim ettiğiniz her belgenin ve makbuzun dijital ve fiziksel kopyalarını saklayın.",
            "Uluslararası Ofis'e doğrudan hangi adres belgesinin sizin konut durumunuza (yurt veya özel kiralama) uyduğunu sorun.",
            "Göç İdaresi yardım hattını (157) telefonunuza kaydedin — bu, spesifik başvurunuzla ilgili sorular için resmi kanaldır."
          ]
        }
      },
      {
        "id": "faq",
        "title": "Sıkça Sorulan Sorular",
        "faq": [
          {
            "question": "Gelmeden önce ayrı bir öğrenci vizesine ihtiyacım var mı?",
            "answer": "Hayır — standart bir giriş vizesi veya vizesiz kalma ile girersiniz, ardından geldikten sonra ikamet izni için başvurursunuz."
          },
          {
            "question": "Başvurum işlenirken Türkiye'den ayrılabilir miyim?",
            "answer": "Bu, spesifik durumunuza ve güncel düzenlemelere bağlıdır — seyahat rezervasyonu yapmadan önce Uluslararası Ofis veya Göç İdaresi yardım hattı ile teyit edin."
          },
          {
            "question": "İznim dolmadan mezun olursam ne olur?",
            "answer": "Bazı üniversitelerin Göç İdaresi'nden aldığı yönlendirmeye göre, kartınızın son kullanma tarihi mezuniyet tarihinizden sonraysa, genellikle kartın süresi dolana kadar kalabilirsiniz — ancak spesifik durumunuzu Uluslararası Ofis'inizle teyit edin."
          }
        ]
      }
    ],
    "sourceNoteText": "Bu rehber genel ulusal süreci özetlemektedir ve resmi hukuki tavsiye değildir. Spesifik durumunuz için her zaman şunu kontrol edin:",
    "sourceLinks": [
      {
        "label": "e-ikamet.goc.gov.tr",
        "href": "https://e-ikamet.goc.gov.tr"
      }
    ]
  },
  "ar": {
    "badgeLabel": "دليل تصريح الإقامة",
    "heroTitle": "تصريح الإقامة",
    "heroDescription": "يرشدك هذا الدليل خلال التقديم على تصريح الإقامة كطالب دولي في تركيا، من أول طلب إلكتروني حتى استلام بطاقتك.",
    "calloutNote": "تُدار عملية تصريح الإقامة على المستوى الوطني من قبل إدارة الهجرة في تركيا، وليس من قبل الجامعات، لذا قد تتغير المتطلبات وتختلف قليلاً حسب المحافظة. تأكد دائماً من الخطوات والمستندات والرسوم الحالية مع المكتب الدولي بجامعة كوجالي ونظام e-ikamet الرسمي قبل موعدك.",
    "sections": [
      {
        "id": "overview",
        "title": "نظرة عامة",
        "paragraphs": [
          "يجب على كل طالب دولي يبقى في تركيا لفترة أطول مما تسمح به تأشيرة الدخول أو فترة الإعفاء من التأشيرة الحصول على تصريح إقامة طالب. لا تصدر تركيا تأشيرة طالب طويلة الأمد بمفردها - تدخل بتأشيرة دخول قصيرة الأمد أو ختم إعفاء من التأشيرة، ثم تتقدم بطلب تصريح الإقامة بعد الوصول.",
          "يتم تقديم الطلب نفسه إلكترونياً عبر نظام e-ikamet الحكومي، وفي معظم الجامعات يقوم المكتب الدولي بجمع مستنداتك الورقية وإرسالها إلى مديرية إدارة الهجرة المحلية نيابة عنك، بدلاً من التعامل المباشر مع مكتب الهجرة."
        ]
      },
      {
        "id": "documents",
        "title": "المستندات المطلوبة",
        "paragraphs": [
          "بينما قد تختلف المتطلبات الدقيقة قليلاً حسب المحافظة، يجب عليك عموماً تجهيز:"
        ],
        "list": {
          "type": "ul",
          "items": [
            "جواز سفرك (الأصل ونسخة من صفحتي الهوية والتأشيرة)",
            "نموذج طلب تصريح الإقامة الموقع الذي ينشئه e-ikamet",
            "شهادة طالب حالية من قسمك",
            "تأمين صحي ساري يستوفي الحد الأدنى من متطلبات التغطية لدى إدارة الهجرة",
            "صور شخصية بيومترية",
            "إثبات العنوان (خطاب سكن جامعي، عقد إيجار موثق، أو فاتورة حسب مكان إقامتك)",
            "إيصال يؤكد دفع رسوم بطاقة تصريح الإقامة"
          ]
        }
      },
      {
        "id": "steps",
        "title": "خطوات التقديم",
        "list": {
          "type": "ol",
          "items": [
            "أنشئ طلبك إلكترونياً على الموقع e-ikamet.goc.gov.tr، واختر \"طلب أول مرة\" لتصريح الطالب.",
            "اطبع ووقّع نموذج الطلب الذي يتم إنشاؤه في النهاية.",
            "اجمع جميع المستندات المطلوبة المذكورة أعلاه.",
            "قدّم مستنداتك إلى المكتب الدولي بجامعة كوجالي ضمن الموعد النهائي الذي يحددونه (تطلب العديد من الجامعات ذلك خلال 15-30 يوماً من إنشاء طلبك الإلكتروني).",
            "ادفع رسوم بطاقة تصريح الإقامة واحتفظ بإيصالك.",
            "انتظر موعدك - تقوم العديد من الجامعات بتقديم ملفات الطلاب دفعة واحدة لمكتب الهجرة بدلاً من إرسالها فردياً.",
            "تابع حالة طلبك على موقع e-ikamet.",
            "بمجرد الموافقة، تُرسل بطاقتك الفعلية بالبريد إلى عنوانك المسجل."
          ]
        }
      },
      {
        "id": "fees",
        "title": "الرسوم",
        "paragraphs": [
          "يحصل الطلاب على معاملة أفضل بكثير من حيث الرسوم مقارنة بمعظم فئات تصريح الإقامة الأخرى: ضريبة تصريح الإقامة (harç) التي تُطبق على الأنواع قصيرة الأمد وغيرها من التصاريح تُعفى عموماً لتصاريح الطلاب، مما يعني أن الطلاب عادة ما يدفعون فقط رسم البطاقة/المستند السنوي الثابت الذي تحدده وزارة المالية.",
          "تتغير رسوم البطاقة هذه كل عام، لذا لا تضع ميزانيتك بناءً على رقم من مقالة مدونة قديمة أو تجربة طالب سابق. تحقق من المبلغ الحالي مباشرة على e-ikamet.gov.tr أو من المكتب الدولي قبل الدفع."
        ]
      },
      {
        "id": "timeline",
        "title": "الجدول الزمني",
        "list": {
          "type": "ul",
          "items": [
            "يجب أن تبدأ طلبك قبل انتهاء تأشيرتك الحالية أو فترة الإقامة بدون تأشيرة - لا تنتظر حتى الأسبوع الأخير.",
            "تحدد معظم الجامعات موعدها النهائي الداخلي الخاص (عادة 15-30 يوماً بعد طلبك الإلكتروني) لتقديم المستندات الورقية إلى المكتب الدولي.",
            "تختلف مدة المعالجة بعد التقديم حسب المحافظة ويمكن أن تتراوح من بضعة أسابيع إلى شهرين.",
            "إذا كنت تجدد تصريحاً حالياً بدلاً من التقديم لأول مرة، ابدأ قبل 60 يوماً على الأقل من انتهاء صلاحية بطاقتك الحالية."
          ]
        }
      },
      {
        "id": "mistakes",
        "title": "الأخطاء الشائعة",
        "list": {
          "type": "ul",
          "items": [
            "الانتظار طويلاً بعد الوصول لبدء الطلب الإلكتروني.",
            "تقديم المستندات إلى المكتب الدولي بعد موعدهم النهائي الداخلي، حتى لو لم تنته صلاحية تأشيرتك بعد.",
            "تأمين صحي لا يستوفي الحد الأدنى من التغطية التي تتطلبها إدارة الهجرة.",
            "عدم إبلاغ مكتب الهجرة بعد تغيير العنوان أو جواز السفر أو القسم.",
            "افتراض أن مبلغ رسوم العام الماضي لا يزال صحيحاً."
          ]
        }
      },
      {
        "id": "tips",
        "title": "نصائح مفيدة",
        "list": {
          "type": "ul",
          "items": [
            "ابدأ طلب e-ikamet في أقرب وقت تسمح به جامعتك - لا تنتظر تذكيراً.",
            "احتفظ بنسخ رقمية وورقية من كل مستند وإيصال تقدمه.",
            "اسأل المكتب الدولي مباشرة عن مستند إثبات العنوان الذي ينطبق على وضعك السكني المحدد (سكن جامعي أو إيجار خاص).",
            "احفظ الخط الساخن لإدارة الهجرة (157) في هاتفك - إنه القناة الرسمية للأسئلة المتعلقة بطلبك المحدد."
          ]
        }
      },
      {
        "id": "faq",
        "title": "الأسئلة الشائعة",
        "faq": [
          {
            "question": "هل أحتاج إلى تأشيرة طالب منفصلة قبل الوصول؟",
            "answer": "لا - تدخل بتأشيرة دخول عادية أو إقامة بدون تأشيرة، ثم تتقدم بطلب تصريح الإقامة بعد وصولك."
          },
          {
            "question": "هل يمكنني مغادرة تركيا أثناء معالجة طلبي؟",
            "answer": "يعتمد هذا على وضعك المحدد واللوائح الحالية - تأكد مع المكتب الدولي أو الخط الساخن لإدارة الهجرة قبل حجز السفر."
          },
          {
            "question": "ماذا يحدث إذا تخرجت قبل انتهاء صلاحية تصريحي؟",
            "answer": "وفقاً لإرشادات تلقتها بعض الجامعات من مكتب الهجرة، إذا كان تاريخ انتهاء صلاحية بطاقتك بعد تاريخ تخرجك، يمكنك عموماً البقاء حتى تنتهي صلاحية البطاقة نفسها - لكن تأكد من حالتك المحددة مع مكتبك الدولي."
          }
        ]
      }
    ],
    "sourceNoteText": "يلخص هذا الدليل العملية الوطنية العامة وليس استشارة قانونية رسمية. لحالتك المحددة، تحقق دائماً من",
    "sourceLinks": [
      {
        "label": "e-ikamet.goc.gov.tr",
        "href": "https://e-ikamet.goc.gov.tr"
      }
    ]
  },
  "ru": {
    "badgeLabel": "Гид по виду на жительство",
    "heroTitle": "Вид на жительство (İkamet)",
    "heroDescription": "Этот гид проведёт вас через оформление вида на жительство как иностранного студента в Турции — от первой онлайн-заявки до получения карты.",
    "calloutNote": "Процесс оформления вида на жительство осуществляется на национальном уровне Управлением по делам миграции Турции, а не отдельными университетами, поэтому требования могут меняться и немного отличаться по провинциям. Всегда уточняйте актуальные шаги, документы и сборы в Международном отделе Университета Коджаэли и в официальной системе e-ikamet перед вашей записью.",
    "sections": [
      {
        "id": "overview",
        "title": "Обзор",
        "paragraphs": [
          "Каждый иностранный студент, остающийся в Турции дольше срока действия въездной визы или безвизового периода, должен получить студенческий вид на жительство. Турция не выдаёт долгосрочную студенческую визу саму по себе — вы въезжаете по краткосрочной визе или без визы, а затем подаёте заявку на вид на жительство после прибытия.",
          "Сама заявка подаётся онлайн через государственную систему e-ikamet, и в большинстве университетов Международный отдел собирает ваши бумажные документы и передаёт их в местное Управление по делам миграции от вашего имени, вместо того чтобы вы напрямую взаимодействовали с миграционной службой."
        ]
      },
      {
        "id": "documents",
        "title": "Необходимые документы",
        "paragraphs": [
          "Точные требования могут немного отличаться по провинциям, но обычно вам нужно подготовить:"
        ],
        "list": {
          "type": "ul",
          "items": [
            "Паспорт (оригинал и копию страниц с личными данными и визой)",
            "Подписанную форму заявления на вид на жительство, сформированную в системе e-ikamet",
            "Действующую студенческую справку с вашего факультета",
            "Действующую медицинскую страховку, соответствующую минимальным требованиям Управления по делам миграции",
            "Биометрические фото",
            "Подтверждение адреса (справка из общежития, нотариально заверенный договор аренды или счёт за коммунальные услуги, в зависимости от места проживания)",
            "Квитанцию об оплате сбора за карту вида на жительство"
          ]
        }
      },
      {
        "id": "steps",
        "title": "Шаги подачи заявки",
        "list": {
          "type": "ol",
          "items": [
            "Создайте заявку онлайн на e-ikamet.goc.gov.tr, выбрав «первая заявка» для студенческого разрешения.",
            "Распечатайте и подпишите форму заявления, сформированную в конце.",
            "Соберите все необходимые документы, перечисленные выше.",
            "Подайте документы в Международный отдел Университета Коджаэли в установленный ими срок (многие университеты требуют этого в течение 15–30 дней после создания онлайн-заявки).",
            "Оплатите сбор за карту вида на жительство и сохраните квитанцию.",
            "Дождитесь записи — многие университеты передают дела студентов в миграционную службу пакетами, а не по отдельности.",
            "Отслеживайте статус заявки на сайте e-ikamet.",
            "После одобрения физическая карта будет отправлена по вашему зарегистрированному адресу."
          ]
        }
      },
      {
        "id": "fees",
        "title": "Сборы",
        "paragraphs": [
          "Студенты получают значительно более выгодные условия по сборам, чем большинство других категорий вида на жительство: сбор за вид на жительство (harç), применяемый к краткосрочным и другим типам разрешений, обычно не взимается со студенческих разрешений, то есть студенты, как правило, платят только фиксированный ежегодный сбор за документ/карту, установленный Министерством финансов.",
          "Этот сбор за карту меняется каждый год, поэтому не планируйте бюджет по цифре из старой статьи в блоге или опыта другого студента. Проверьте актуальную сумму напрямую на e-ikamet.gov.tr или в Международном отделе перед оплатой."
        ]
      },
      {
        "id": "timeline",
        "title": "Сроки",
        "list": {
          "type": "ul",
          "items": [
            "Вы должны начать заявку до истечения срока действия визы или безвизового пребывания — не ждите до последней недели.",
            "Большинство университетов устанавливают собственный внутренний срок (обычно 15–30 дней после онлайн-заявки) для подачи бумажных документов в Международный отдел.",
            "Время обработки после подачи варьируется по провинциям и может занять от нескольких недель до пары месяцев.",
            "Если вы продлеваете существующее разрешение, а не подаёте заявку впервые, начните минимум за 60 дней до истечения срока действия текущей карты."
          ]
        }
      },
      {
        "id": "mistakes",
        "title": "Частые ошибки",
        "list": {
          "type": "ul",
          "items": [
            "Слишком долгое ожидание после прибытия перед началом онлайн-заявки.",
            "Подача документов в Международный отдел после их внутреннего срока, даже если виза ещё не истекла.",
            "Медицинская страховка, не соответствующая минимальным требованиям Управления по делам миграции.",
            "Отсутствие уведомления миграционной службы после смены адреса, паспорта или факультета.",
            "Предположение, что сумма сбора прошлого года всё ещё актуальна."
          ]
        }
      },
      {
        "id": "tips",
        "title": "Полезные советы",
        "list": {
          "type": "ul",
          "items": [
            "Начните заявку на e-ikamet как можно раньше, насколько позволяет университет — не ждите напоминания.",
            "Храните цифровые и бумажные копии каждого документа и квитанции, которые вы подаёте.",
            "Спросите напрямую в Международном отделе, какой документ подтверждения адреса подходит именно для вашей ситуации с жильём (общежитие или частная аренда).",
            "Сохраните номер горячей линии миграционной службы (157) в телефоне — это официальный канал для вопросов по вашей конкретной заявке."
          ]
        }
      },
      {
        "id": "faq",
        "title": "Часто задаваемые вопросы",
        "faq": [
          {
            "question": "Нужна ли мне отдельная студенческая виза перед приездом?",
            "answer": "Нет — вы въезжаете по стандартной въездной визе или в безвизовом режиме, а затем подаёте заявку на вид на жительство после прибытия."
          },
          {
            "question": "Могу ли я покинуть Турцию, пока моя заявка обрабатывается?",
            "answer": "Это зависит от вашей конкретной ситуации и текущих правил — уточните в Международном отделе или на горячей линии миграционной службы перед бронированием поездки."
          },
          {
            "question": "Что произойдёт, если я выпущусь до истечения срока действия разрешения?",
            "answer": "Согласно рекомендациям, которые некоторые университеты получили от миграционной службы, если срок действия вашей карты истекает после даты выпуска, вы, как правило, можете оставаться до истечения срока действия самой карты — но уточните свой конкретный случай в Международном отделе."
          }
        ]
      }
    ],
    "sourceNoteText": "Этот гид обобщает общий национальный процесс и не является официальной юридической консультацией. Для вашего конкретного случая всегда проверяйте",
    "sourceLinks": [
      {
        "label": "e-ikamet.goc.gov.tr",
        "href": "https://e-ikamet.goc.gov.tr"
      }
    ]
  }
};
